modLoader = "javafml"
loaderVersion = "[28,)"
issueTrackerURL = "https://github.com/TechnicianLP/ReAuth/issues"

[[mods]]
modId = "reauth"
version = "${file.jarVersion}"
displayName = "ReAuth"
updateJSONURL = "https://raw.githubusercontent.com/TechnicianLP/ReAuth/master/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/reauth"
authors = "TechnicianLP"
description = "A Mod to renew your Session"

[[dependencies.reauth]]
modId = "minecraft"
mandatory = true
versionRange = "[1.14,1.16)"
ordering = "NONE"
side = "CLIENT"
